### ISSUE TITLE
$HOME/QuickPiperAudiobook/piper directory not found on first run

### ISSUE THREAD

**Issue by vin-cf** [C-Loftus/QuickPiperAudiobook#2]
OS: Fedora 40
Go version: go version go1.23.2 linux/amd64

I have cloned the repo, installed [go](https://go.dev/doc/install) and [calibre](https://calibre-ebook.com/download_linux)

When I run `./QuickPiperAudiobook ebook.pub`, I get the following error

```
No output value specified, default from config file: ~/Audiobooks
Using model specified in config file: en_US-hfc_male-medium.onnx
Downloading en_US-hfc_male-medium.onnx to /home/foo/.config/QuickPiperAudiobook/en_US-hfc_male-medium.onnx
Finished downloading successfully.
Downloading en_US-hfc_male-medium.onnx.json to /home/foo/.config/QuickPiperAudiobook/en_US-hfc_male-medium.onnx.json
Finished downloading successfully.
Converting ebook.epub to the proper intermediary text format...
Text conversion completed successfully.
Converting your file to an audiobook... This may take a while!
Error: failed to run piper command: chdir /home/foo/.config/QuickPiperAudiobook/piper: no such file or directory
```

When I create the `/home/foo/.config/QuickPiperAudiobook/piper` directory, I get the following error: 
```
|Error: failed to run piper command: fork/exec /home/foo/.config/QuickPiperAudiobook/piper/piper: no such file or directory
```

When I create the ` /home/foo/.config/QuickPiperAudiobook/piper/piper` directory, I get the following permissions error and am unable to create an audiobook.
```
|Error: failed to run piper command: fork/exec /home/foo/.config/QuickPiperAudiobook/piper/piper: permission denied
```

**Comment by Ozymandyaz** [comment]
Same issue on two Arch installs... However, if I manually go to to the URL in piper.go (https://github.com/rhasspy/piper/releases/download/v1.2.0/piper_amd64.tar.gz) and unzip the .gz file into  ~/.config/QuickPiperAudiobook/piper it works. My guess in that PiperIsInstalled is not always working...

**Comment by vin-cf** [comment]
I have deleted the contents of ` ~/.config/QuickPiperAudiobook/` and ran audiobook generation again.  

Generation fails, the contents of the folder are:

```
host@computer cd ~/.config/QuickPiperAudiobook/ &&  tree -L 2
.
├── config.yaml
├── en_US-hfc_male-medium.onnx
└── en_US-hfc_male-medium.onnx.json

```

**Comment by C-Loftus** [comment]
Thanks for reporting this. I should have it fixed now in the latest release. Please reopen if you find differently.
