### ISSUE TITLE
Not enough input options and tts quality

### ISSUE THREAD

**Issue by sheerun** [C-Loftus/QuickPiperAudiobook#5]
While I appreciate project, it would be nice if it:

- supported .html websites with to text conversion using something like pandoc or html2text (with ability to choose backend)
- supported state of art text to speech like coqui xttsv2, tortoise tts, or opentts

you can also consider non-open source backends for tts for now as they are ahead, like chatgpt api, eleven apps api, or one of [many tts extensions suported by silly tavern](https://github.com/SillyTavern/SillyTavern/tree/ba6f7b7a98cf7a5eaf4f0e81da9779a9a668ced4/public/scripts/extensions/tts) (both open source and not, like adapters to openai api)

thanks

**Comment by C-Loftus** [comment]
Thanks for your feedback! Here are some thoughts:

> supported .html websites with to text conversion using something like pandoc or html2text (with ability to choose backend)

We currently have HTML support but it is relatively unsophisticated. You just need to make sure the local file or URL has the `.html` extension at the end. 
* i.e. Download a HTML page like the following, then run `QuickPiperAudiobook Immanuel\ Kant\ -\ Wikipedia.html` will convert the local HTML file to an audiobook

To do more complicated parsing and speak only non-visual readable content, I think it becomes non-trivial and requires looking at semantic HTML/aria roles like a screen reader would. However, I am also interested in this and think its a good/useful idea.

> supported state of art text to speech like coqui xttsv2, tortoise tts, or opentts

I would be happy to look into this for you. Could you please provide a ranking of which models you would like the most with some tradeoffs in mind? I would prefer to support models that are offline (or very cheap as a SaaS), multilingual, and fast to generate audiobooks with.  

In the past I've found state of the art models to be difficult to package, too slow/power intensive for making audiobooks in a reasonable amount of time, or requiring expensive GPUs. I find openai and 11elevenlabs to be too expensive to be practical.

Thank you for your perspective

**Comment by C-Loftus** [comment]
Going to close this. If you see this again and want to provide input, feel free and I will reopen and can read over anything. Otherwise I think I am likely to keep the current setup of just piper since I don't see any other models as being practical for generating audiobooks offline. Happy to be shown I am wrong though!
