### ISSUE TITLE
Audiobook output not written to disk if the default ~/Audiobooks directory does not exist

### ISSUE THREAD

**Issue by vin-cf** [C-Loftus/QuickPiperAudiobook#6]
Using: [v0.0.2](https://github.com/C-Loftus/QuickPiperAudiobook/releases/tag/v0.0.2)

If the folder to write the audiobook output to does not exist, the audio is generated but no file is written to disk.

Reprodution steps:
```
 ./QuickPiperAudiobook  Making\ Music\ -\ 74\ Creative\ Strategies\ for\ Electronic\ Music\ Producers.pdf 
No output value specified, default from config file: ~/Audiobooks
```
Result: Audiobook output not written to the default ~/Audiobooks directory

Perhaps there should be a check to see if the default folder (`~/Audiobooks`) or the specified directory exists, and/or an action to create the directory if it doesn't exist.

**Comment by C-Loftus** [comment]
Thanks for reporting. Should be fixed in latest release I just pushed
