### ISSUE TITLE
Missing Polish special characters like: łąęćźż from source material (UTF-8 PDF, txt, html)

### ISSUE THREAD

**Issue by w84death** [C-Loftus/QuickPiperAudiobook#8]
I got perfectly fine PDF, opening it in Calibre's viewer shows proper characters.
I tested two Polish models: Gosia (medium) and  mls_6892 (low)
Language: pl_PL (Polish, Polish)

They read all text with characters replaced by the non special equivalents. Instead of "ł" got "l" in "łódź" model reads "lodz". 

Did i miss some configuration value? Do internals use UTF-8 on all steps?

Test 2: new .txt
I created new text file with UTF-8 encoding and write some Polish words. Same problem.

Test 3: html file
Proper HTML with encoding   <meta charset="UTF-8">, same problem.

PC Ubuntu LTS, ThinkPad: Debian 12

**Comment by C-Loftus** [comment]
Thanks for the report. Please try the `--speak-diacritics` flag. (Check out `--help` if you are unclear on usage)

By default we transliterate special characters since I was finding they mess up the audio output in English.

**Comment by w84death** [comment]
Thanks, did not know that diacritics is the name for this :)

Got this error when using diacritics:
```
kj@x220:~/Audiobooks$ ./QuickPiperAudiobook-linux-amd64 --speak-diacritics --model=pl_PL-mls_6892-low.onnx  polski.txt
No output value specified, default from config file: ~/Audiobooks
Converting polski.txt to the proper intermediary text format...
Text conversion completed successfully.
Error: failed to read file passed as input to piper: read /tmp/ebook-convert-1620853618.txt: file already closed

```


```
 kj@x220:~/Audiobooks$ ls -l /tmp/ebook-convert-1620853618.txt 
-rw------- 1 kj kj 385 Oct  9 09:43 /tmp/ebook-convert-1620853618.txt
```
Inside this temp file is a copy of the polish.txt with proper characters.


So we are closer to resolve this!

**Comment by C-Loftus** [comment]
Thanks for checking that. I will take a look at this when I have some extra time. I think this should be a simple fix.

**Comment by C-Loftus** [comment]
I have fixed this in the latest release https://github.com/C-Loftus/QuickPiperAudiobook/releases/tag/v0.0.4 
If you think the readme should be edited I would be happy to accept a PR so I can credit you :smiley: otherwise I may add it myself in the coming days

The setting is now named `--speak-utf-8` to make it more clear what is going on.
